import uuid
from sqlalchemy import String, DateTime, ForeignKey, Text, func, JSON
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from typing import Optional

from app.db.base import Base

class ChatMessage(Base):
    __tablename__ = "chat_messages"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )

    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    #User or chatbot
    role: Mapped[str] = mapped_column(
        String(10),
        nullable=False
    )

    #message content
    text: Mapped[str] = mapped_column(
        Text,
        nullable=False
    )

    # Structured chart data for visualizations (bot messages only)
    chart_data: Mapped[Optional[dict]] = mapped_column(
        JSON,
        nullable=True,
        default=None
    )

    # Suggested follow-up questions generated by the AI (bot messages only)
    follow_up_questions: Mapped[Optional[list]] = mapped_column(
        JSON,
        nullable=True,
        default=None
    )

    created_at: Mapped[DateTime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False
    )