import uuid
from sqlalchemy import String, Boolean, DateTime, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base

class ChatSession(Base):
    __tablename__ = "chat_sessions"

    #UUID primary key
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )

    #User id links each session to the user who created it
    # CASCADE means that the sessions are deleted if the user is deleted.
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    #Name of chat 
    chat_title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        default="New Chat"
    )

    #Set when the session row is created
    # Allows for the ability to sort chats
    created_at: Mapped[DateTime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False
    )

    #Updated every time a new message is added to a chat.
    last_message_at: Mapped[DateTime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False
    )

    #Allows users to pin chats
    is_pinned: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False
    )

    #Allows users to archive chats
    is_archived: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False
    )

    #brief summary of chat, generated by after certain number of msgs
    chat_summary: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        default="No summary available."
    )

    #If title has been edited by user, generated title will not override
    title_is_user_edited: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False
    )
